### ISSUE TITLE
Auto-sort the imports

### ISSUE THREAD

**Issue by pawamoy** [qtile/qtile#1625]
Quality approach again (#1618, #1623): would you consider using a tool like [isort](https://github.com/timothycrosley/isort) to automatically order the imports?

With the following options:

```toml
[tool.isort]
line_length = 120
not_skip = "__init__.py"
multi_line_output = 3
force_single_line = false
balanced_wrapping = true
default_section = "THIRDPARTY"
known_first_party = "libqtile"
include_trailing_comma = true
```

`isort -y -rc libqtile` will do things like

```diff
diff --git a/libqtile/backend/x11/xcbq.py b/libqtile/backend/x11/xcbq.py
index 10f55586..217d206c 100644
--- a/libqtile/backend/x11/xcbq.py
+++ b/libqtile/backend/x11/xcbq.py
@@ -34,25 +34,23 @@
     A minimal EWMH-aware OO layer over xcffib. This is NOT intended to be
     complete - it only implements the subset of functionalty needed by qtile.
 """
-from collections import OrderedDict
-from itertools import repeat, chain
-import operator
 import functools
+import operator
 import typing
+from collections import OrderedDict
+from itertools import chain, repeat
 
-from xcffib.xproto import CW, WindowClass, EventMask
-from xcffib.xfixes import SelectionEventMask
-
+import cairocffi
+import cairocffi.xcb
 import xcffib
 import xcffib.randr
 import xcffib.xinerama
 import xcffib.xproto
-
-import cairocffi
-import cairocffi.xcb
-
 from libqtile import xkeysyms
 from libqtile.log_utils import logger
+from xcffib.xfixes import SelectionEventMask
+from xcffib.xproto import CW, EventMask, WindowClass
+
 from .xcursors import Cursors
 
 keysyms = xkeysyms.keysyms
```

From `git diff --stat`: 86 files changed, 210 insertions(+), 214 deletions(-).

Isort organizes the imports into three (or more) categories: standard lib, [known frameworks, ] third-party, current package.

In CI you can check it's properly formatted with `isort -c -rc libqtile`.
